[package]
name = "violet"
version = "0.0.1"
authors = ["Jack Coulter <jscinoz@jscinoz.so>"]
keywords = ["pidgin", "purple", "libpurple"]

[dependencies]
clippy = "*"
libpurple-sys = { path = "libpurple-sys" }
